cross_validation:
  enabled: true
  gap_years: 0
  group_column: patient_id
  method: time_series
  n_splits: 3
  test_size: 0.3
dask_config:
  enabled: false
  memory_limit: 256MB
  n_workers: 1
  processes: false
  threads_per_worker: 1
data_generation:
  batch_size: 50
  missing_values:
    enabled: true
    rates:
      blood_pressure: 0.05
      bmi: 0.05
      cholesterol: 0.05
      glucose: 0.05
  n_workers: 1
  num_patients: 100
  output_format: parquet
  partition_by:
  - year
  target_prevalence: 0.1
  use_dask: false
  years_per_patient: 2
feature_selection:
  enabled: true
  estimator: lightgbm
  memory_limit_gb: 0.5
  method: rfe
  n_features: 10
hyperparameter_optimization:
  enabled: false
  engine: optuna
  n_trials: 5
  timeout: 300
imbalance:
  method: smote
  smote:
    k_neighbors: 3
    random_state: 42
    sampling_strategy: 0.5
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
mlflow:
  artifact_location: file:///app/mlruns
  enabled: true
  experiment_name: clinical_ml_docker_test
  tracking_uri: file:///app/mlruns
models:
  catboost:
    enabled: false
  lightgbm:
    enabled: true
    hpo:
      enabled: false
    params:
      bagging_fraction: 0.8
      bagging_freq: 5
      boosting_type: gbdt
      feature_fraction: 0.8
      lambda_l1: 0.1
      lambda_l2: 0.1
      max_depth: 3
      metric: binary_logloss
      min_data_in_leaf: 5
      min_gain_to_split: 0.0
      num_leaves: 10
      objective: binary
      verbose: -1
  xgboost:
    enabled: false
performance:
  early_stopping: true
  early_stopping_rounds: 10
  memory_limit_gb: 0.5
  n_jobs: 1
preprocessing:
  categorical_encoding:
    drop_first: true
    handle_unknown: ignore
    method: onehot
  missing_values:
    strategy: median
  scaling:
    feature_range: null
    method: standard
  temporal_features:
    aggregations:
    - mean
    enabled: true
    window_years: 2
random_seed: 42
threshold_optimization:
  cv_folds: 3
  enabled: true
  method: f1
